# Nuestro proyecto usa Bun para instalar dependencias, así que
# usamos la imagen de contenedor correcta.
image: oven/bun:latest
create-pages:
  pages:
    # La carpeta donde se encuentran los archivos de la página
    # después de ser compilada:
    publish: dist
  rules:
    # Solo actualizamos la página cuando hay cambios a la rama
    # principal.
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  # Comandos que necesitan ejecutarse antes de la compilación:
  before_script:
    - bun i
  # Compilación:
  script:
    - bun run build
